version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.minidev:json-smart
    versions:
    - 2.4.2
    - 2.4.4
    - 2.4.5
  - dependency-name: io.micrometer:micrometer-registry-prometheus
    versions:
    - 1.6.5
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-joda
    versions:
    - 2.12.2
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.19.0
  - dependency-name: org.springframework.boot:spring-boot-starter-webflux
    versions:
    - 2.4.4
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - 3.12.0
  - dependency-name: net.logstash.logback:logstash-logback-encoder
    versions:
    - "6.6"
  - dependency-name: net.javacrumbs.shedlock:shedlock-provider-mongo
    versions:
    - 4.15.0
    - 4.20.0
    - 4.22.1
  - dependency-name: net.javacrumbs.shedlock:shedlock-spring
    versions:
    - 4.15.0
    - 4.20.0
    - 4.22.1
  - dependency-name: com.nimbusds:nimbus-jose-jwt
    versions:
    - 9.4.1
    - 9.4.2
    - "9.5"
    - "9.6"
    - "9.7"
    - "9.8"
    - 9.8.1
  - dependency-name: org.modelmapper:modelmapper
    versions:
    - 2.3.9
    - 2.4.0
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.3
    - 2.4.4
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: com.konghq:unirest-objectmapper-jackson
    versions:
    - 3.11.02
    - 3.11.11
  - dependency-name: com.konghq:unirest-java
    versions:
    - 3.11.02
    - 3.11.11
  - dependency-name: com.sun.xml.bind:jaxb-core
    versions:
    - 3.0.0
  - dependency-name: com.sun.xml.bind:jaxb-impl
    versions:
    - 3.0.0
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
  - dependency-name: com.github.jsonzou:jmockdata
    versions:
    - 4.3.0
  - dependency-name: de.codecentric:spring-boot-admin-starter-client
    versions:
    - 2.4.0
  - dependency-name: de.codecentric:spring-boot-admin-starter-server
    versions:
    - 2.4.0
  - dependency-name: com.forgerock.openbanking:eidas-psd2-cert
    versions:
    - "1.24"
    - "1.27"
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.10
    - 2.10.9
  - dependency-name: com.maxmind.geoip2:geoip2
    versions:
    - 2.15.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.apache.httpcomponents:httpmime
    versions:
    - 4.5.13
  - dependency-name: org.apache.httpcomponents:httpclient
    versions:
    - 4.5.13
  - dependency-name: dev.openbanking4.spring.security:spring-security-multi-auth-starter
    versions:
    - 2.2.4.0.0.1
